### ISSUE TITLE
[Feature Request] Config Sorting

### ISSUE THREAD

**Issue by NielsPilgaard** [zeroneye/Powah#42]
Hello o/

I would like to request that the configs get sorted by tier.

At the moment the configs are ordered like this:

```toml
[Energy_Transfer]
	#Range: 1 ~ 9000000000000000000
	spiritedTransfer = 32000
	#Range: 1 ~ 9000000000000000000
	starterTransfer = 1000
	#Range: 1 ~ 9000000000000000000
	basicTransfer = 2000
	#Range: 1 ~ 9000000000000000000
	hardenedTransfer = 4000
	#Range: 1 ~ 9000000000000000000
	nioticTransfer = 16000
	#Range: 1 ~ 9000000000000000000
	blazingTransfer = 8000
	#Range: 1 ~ 9000000000000000000
	nitroTransfer = 64000
```

and I would like

```toml
[Energy_Transfer]
	#Range: 1 ~ 9000000000000000000
	starterTransfer = 1000
	#Range: 1 ~ 9000000000000000000
	basicTransfer = 2000
	#Range: 1 ~ 9000000000000000000
	hardenedTransfer = 4000
	#Range: 1 ~ 9000000000000000000
	blazingTransfer = 8000
	#Range: 1 ~ 9000000000000000000
	nioticTransfer = 16000
	#Range: 1 ~ 9000000000000000000
	spiritedTransfer = 32000
	#Range: 1 ~ 9000000000000000000
	nitroTransfer = 64000
```

I hope you'll consider it :)
